- azure/azure-pr-pipeline.yml
- azure/azure-release-pipeline.yml
> AMB-831 pr and release only internal-dev

- azure/azure-release-pipeline.yml
> AMB-831 fix indentation

- azure/azure-release-pipeline.yml
> AMB-831 add internal-qa release

- azure/azure-release-pipeline.yml
- manifest_template.yml
> Amb 831 deploy transformation engine

- azure/azure-pr-pipeline.yml
- azure/azure-release-pipeline.yml
- azure/templates/run-tests.yml
- poetry.lock
- proxies/live/apiproxy/policies/RaiseFault.InvalidAcceptHeader.xml
- proxies/live/apiproxy/policies/RaiseFault.InvalidContentType.xml
- proxies/live/apiproxy/proxies/default.xml
- proxies/live/apiproxy/targets/fc-target.xml
- pyproject.toml
- tests/configuration/config.py
- tests/configuration/environment.py
- tests/conftest.py
- tests/test_convert.py
> AMB-829 reject invalid header values

- azure/templates/run-tests.yml
- poetry.lock
- proxies/live/apiproxy/policies/AssignMessage.Errors.CatchAllMessage.xml
- proxies/live/apiproxy/policies/RaiseFault.InvalidAcceptHeader.xml
- proxies/live/apiproxy/policies/RaiseFault.InvalidContentType.xml
- proxies/live/apiproxy/targets/fc-target.xml
- pyproject.toml
- tests/api_tests.py
- tests/test_convert.py
> AMB-829 change error messages to FHIR

- Makefile
- azure/templates/run-tests.yml
> AMB-846 enable tests for int env

- tests/configuration/cmd_options.py
> AMB-846 fix renaming client-id to default-client-id

- tests/configuration/cmd_options.py
> AMB-846 fix renaming client-secret to default-client-secret

- package-lock.json
- package.json
- poetry.lock
run "npm update" and 'poetry update' to update dependencies
> amb-942-update-repo-dependencies

- docker/Transformation-Engine/src/test/java/nhsd/fhir/transformationenginepoc/service/ConverterTest.java
- docker/Transformation-Engine/src/test/resources/GPConnect/Patient_GPConnect.json
> AMB-959 prove extensions are carried over when using convert

- specification/fhir-converter.yaml
> AMB-964 Spec improvements

- specification/fhir-converter.yaml
> AMB-1012 Spec: change status and roadmap wording

- manifest_template.yml
- proxies/live/apiproxy/policies/OAuthV2.VerifyAccessToken.xml
Enforce app restricted access to proxy
> AMB-1016 enforce app restricted scope

- .gitignore
- docker/Transformation-Engine/src/main/kotlin/net/nhsd/fhir/converter/transformer/careconnect_transformers.kt
- docker/Transformation-Engine/src/test/kotlin/net/nhsd/fhir/converter/transformer/CareconnectExampleLoader.kt
- docker/Transformation-Engine/src/test/kotlin/net/nhsd/fhir/converter/transformer/lastIssueDate_test.kt
- docker/Transformation-Engine/src/test/kotlin/net/nhsd/fhir/converter/transformer/repeatInformation_test.kt
Transforming medication statement last issue date extension
> add lastIssueDate extension transformation and test

- docker/Transformation-Engine/src/main/kotlin/net/nhsd/fhir/converter/transformer/CareconnectTransformer.kt
- docker/Transformation-Engine/src/main/kotlin/net/nhsd/fhir/converter/transformer/careconnect_transformers.kt
- docker/Transformation-Engine/src/test/kotlin/net/nhsd/fhir/converter/transformer/CareconnectExampleLoader.kt
- docker/Transformation-Engine/src/test/kotlin/net/nhsd/fhir/converter/transformer/prescribing_agency_test.kt
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationstatement/input/MedicationStatementPrescribingAgency-Extension-3to4_003.json
> AMB-1032 add prescribingAgency extension

- docker/Transformation-Engine/src/main/kotlin/net/nhsd/fhir/converter/transformer/careconnect_transformers.kt
- docker/Transformation-Engine/src/test/kotlin/net/nhsd/fhir/converter/transformer/allergyIntoleranceEnd.kt
> AMB-1026 add transform for allergyIntoleranceEnd

- docker/Transformation-Engine/src/main/kotlin/net/nhsd/fhir/converter/transformer/careconnect_transformers.kt
- docker/Transformation-Engine/src/test/kotlin/net/nhsd/fhir/converter/transformer/evidence_test.kt
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/allergyintolerance/input/AllergyIntoleranceEvidence-Extension-3to4_000.json
Transforming allergyIntolerance evidence extension
> Amb 1027 allergy evidence extension

- docker/Transformation-Engine/src/main/kotlin/net/nhsd/fhir/converter/transformer/careconnect_transformers.kt
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/expected/MedicationRequestStatusReason-Extension-3to4_000.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/expected/MedicationRequestStatusReason-Extension-3to4_001.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/input/MedicationRequestPrescriptionType-Extension-3to4_000.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/input/MedicationRequestPrescriptionType-Extension-3to4_001.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/input/MedicationRequestPrescriptionType-Extension-3to4_002.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/input/MedicationRequestPrescriptionType-Extension-3to4_003.json
* Update from the first iteration. The inner extension now belongs to the coding object.
> Refactoring mapping to include extension as element of Coding object

- docker/Transformation-Engine/src/main/kotlin/net/nhsd/fhir/converter/transformer/CareconnectTransformer.kt
- docker/Transformation-Engine/src/main/kotlin/net/nhsd/fhir/converter/transformer/Transformer.kt
- docker/Transformation-Engine/src/main/kotlin/net/nhsd/fhir/converter/transformer/careconnect_transformers.kt
- docker/Transformation-Engine/src/test/kotlin/net/nhsd/fhir/converter/transformer/CareconnectTransformerTest.kt
- docker/Transformation-Engine/src/test/kotlin/net/nhsd/fhir/converter/transformer/allergy_intolerance_coding_test.kt
- docker/Transformation-Engine/src/test/kotlin/net/nhsd/fhir/converter/transformer/descriptionId_descriptionDisplay_test.kt
- docker/Transformation-Engine/src/test/kotlin/net/nhsd/fhir/converter/transformer/statusReason_test.kt
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/expected/MedicationRequestStatusReason-Extension-3to4_000.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/expected/MedicationRequestStatusReason-Extension-3to4_001.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/expected/MedicationRequestStatusReason-Extension-3to4_002.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/expected/MedicationRequestStatusReason-Extension-3to4_003.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/expected/MedicationRequestStatusReason-Extension-3to4_004.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/expected/MedicationRequestStatusReason-Extension-3to4_005.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/expected/MedicationRequestStatusReason-Extension-3to4_006.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/expected/MedicationRequestStatusReason-Extension-3to4_007.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/expected/MedicationRequestStatusReason-Extension-3to4_008.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/expected/MedicationRequestStatusReason-Extension-3to4_009.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/expected/MedicationRequestStatusReason-Extension-3to4_010.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/expected/MedicationRequestStatusReason-Extension-3to4_011.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/expected/MedicationRequestStatusReason-Extension-3to4_012.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/expected/MedicationRequestStatusReason-Extension-3to4_013.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/expected/MedicationRequestStatusReason-Extension-3to4_014.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/expected/MedicationRequestStatusReason-Extension-3to4_015.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/input/MedicationRequestPrescriptionType-Extension-3to4_000.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/input/MedicationRequestPrescriptionType-Extension-3to4_001.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/input/MedicationRequestPrescriptionType-Extension-3to4_002.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/input/MedicationRequestPrescriptionType-Extension-3to4_003.json
- docker/Transformation-Engine/src/test/resources/careconnect-to-ukcore/medicationrequest/maps/MedicationRequestStatusReason-Extension-3to4.map
- docker/Transformation-Engine/src/test/resources/extra-examples/expected/AllergyIntoleranceExtensionId-Extension-3to4_000.json
- docker/Transformation-Engine/src/test/resources/extra-examples/input/AllergyIntoleranceExtensionId-Extension-3to4_000.json
> Amb 1028 update iops examples

- docker/Transformation-Engine/src/main/kotlin/net/nhsd/fhir/converter/transformer/CareconnectTransformer.kt
- docker/Transformation-Engine/src/main/kotlin/net/nhsd/fhir/converter/transformer/Transformer.kt
- docker/Transformation-Engine/src/test/kotlin/net/nhsd/fhir/converter/transformer/CareconnectTransformerTest.kt
> AMB-000 apply transformer for AllergyIntolerance:coding:extension

- specification/fhir-converter.yaml
> AMB-954 minor correction

- manifest_template.yml
> AMB-000 add fhir converter to api catalogue

- specification/fhir-converter.yaml
> AMB-000 AMP-941 API Specs - add Errors section

- .github/workflows/continuous-integration.yml
- package-lock.json
- specification/fhir-converter.yaml
> Updated spec file to reflect retired status
